version: '3'
services:
  dtupayapi:
    container_name: dtupay-customer-rest-api
    image: lagos/dtupay-customer-rest-api
    ports:
      - "8080:8080"
    networks:
      - "dtupay-network"

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
    networks:
      - "dtupay-network"

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - "dtupay-network"


networks:
  dtupay-network: