version: '3'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    hostname: "rabbit1"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - "dtupay-network"

  dtupay-bank:
    container_name: dtupay-bank
    image: lagos/dtupay-bank
    environment:
      - BROKER_NAME=rabbitmq
    networks:
      - "dtupay-network"
    depends_on:
      - rabbitmq

  dtupay-token:
    container_name: tokencucomber
    image: lagos/tokencucomber
    environment:
      - BROKER_NAME=rabbitmq
    networks:
      - "dtupay-network"
    depends_on:
      - rabbitmq
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootPassXXX
    ports:
      - "27017:27017"
    volumes:
      - "./mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
    networks:
      - "dtupay-network"

  dtupay-api-customer:
    container_name: dtupay-api-customer
    image: lagos/dtupay-api-customer
    ports:
      - "8080:8080"
    networks:
      - "dtupay-network"
    depends_on:
      - dtupay-bank
      - dtupay-token

  dtupay-api-merchant:
    container_name: dtupay-api-merchant
    image: lagos/dtupay-api-merchant
    ports:
      - "8081:8080"
    networks:
      - "dtupay-network"
    depends_on:
      - dtupay-bank
      - dtupay-token

  dtupay-api-manager:
    container_name: dtupay-api-manager
    image: lagos/dtupay-api-manager
    ports:
      - "8082:8080"
    networks:
      - "dtupay-network"
    depends_on:
      - dtupay-bank
      - dtupay-token

networks:
  dtupay-network: